In [13]:
l = [5,8,2,4,7,9]
result = 0
for i in range(len(l)):
    result+=l[i]
print(result)

35


In [14]:
l = [5,8,2,4,7,9]
result = 1
for i in range(len(l)):
    result*=l[i]
print(result)

20160


In [18]:
import numpy as np
arr=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(arr)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [21]:
#a
np.sort(arr, axis=None)

array([1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9,
       9])

In [25]:
#b
np.sort(arr[:,1])

array([5, 7, 7, 9])

In [26]:
#c
np.sort(arr[2])

array([2, 4, 6, 7, 8, 8])

In [27]:
#d
arr[1:,...]

array([[7, 7, 5, 3, 5, 7],
       [8, 7, 8, 4, 2, 6],
       [9, 9, 7, 3, 1, 4]])

In [29]:
#e
arr[...,2:]

array([[8, 8, 9, 8],
       [5, 3, 5, 7],
       [8, 4, 2, 6],
       [7, 3, 1, 4]])

In [32]:
#f
arr**2

array([[25, 25, 64, 64, 81, 64],
       [49, 49, 25,  9, 25, 49],
       [64, 49, 64, 16,  4, 36],
       [81, 81, 49,  9,  1, 16]], dtype=int32)

In [33]:
#g
arr[2,3]

4

In [35]:
#h
arr.sum()

145

In [36]:
#i
arr.ndim

2

In [42]:
#j
arr.dtype

dtype('int32')

In [40]:
#k
arr.nbytes

96